language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.4.1
  - rvm use 2.4.1 --fuzzy
  - export GEMDIR=$(rvm gemdir)

before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gem install bundler
  - bundle install
  - chmod +x ./travis.sh

script: "./travis.sh"

branches:
  only:
    - dev

env:
  global:
    - secure: JxS7Lpja5WtmvWCK3BAtSOchWnyrHWsECqIr7N2MiO+njQLaOYDkKF9nkCaF5lwJLGf5Fk84Kh/mx6sDcB9Vw0EyzT0yjLPExhF4k20ZI5SxJmt882FGw5NPwr8deWJM7KqntsyTK8MVcJNao5qycvyXeD80xD4/qhDOJ82YK8iBo/YR7CcUR7vxHFh0tjGj7YFRMwlZQkpxirUVdksFyUH9vsCEepWwIkbD/5ovICgGMtiEY3/yMcjzDaBwDT+CyupTacC1QhgsIGbxmfhqeAfYZCxqUNql6sNpQYuCfVtSJCXIMYom8zkAECD2GVX0JFLZVQYK235t5VREqAM/jhqqZT4WLKGj7hH3qOVnT7k+FublfyW+IhgxLQh72u7W7ZLQkgthIMADkjOZoVIHgfh7sp5J8Kh3Slb8LQKbrOBzVy/TSLj2H4U6588mC5Ddid76ro4M74vfprsRgJe8JwrIq7+szgklgiX3jcYmrOA8zhjtlxSpykLLYGxhM78Rj0QNnOszBSmuzay+bmev15yP9eUBPspaUbCKUacEaN/DMnVdxZPTKlqPmukVpXEEms4sqWMnTkHRottNM4GWCz1wCo+E8uroE+O1rge582TjkJHvmiGMcOsHMCgBcTJHCxC0ce4cUuKZi4FIX8nCQHml3yCCynZcUIQNPagKjmY=
    - JEKYLL_ENV=production
    - JEKYLL_LOG_LEVEL=debug
    - GH_REF=github.com/neard/neard.github.io.git
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  webhooks:
    secure: HywvYnPP52FdkQTvG0fAZlKdMfpuu/M/3DRNlb0kXaEqQb664mLccPBWYoLL/RnKfI5F/BHAQ/BlfZhJcOfqRRwewV0oK+Ni6SX1X0bIOgTTYWtwYiiD2hc5Uib+pQuw+NBVRJKF4RI55vy1nRbLG5Ig8P/59gs8q08Z/swCi1CcgT742hXbb2u3FzT9kZINR60lwoAfqceAtt3/g2KlJpLF6eC2RYZqWgEJBVasz6DCmJhk3KvmTQvImzgO57lrcDP/xeUPsZE16fC3NPmPLx19uHQruj71hSSybFjaI2xLdwWy3lYhIRRdHNA9YZcqUy7+PbAfQwYuVVqpqWpvN7LFgirBvb2IDw2PRI3x5HAi3n/PElN5vIqy7SbKhHzrMB+C6Ccx3VFAlAGPU1F4Pj795mii05mQGiHtHQNiXJ7AwaxYADtVnNjsGwYu0i+GdWGuOP9AO39+ASAF72vocUEv/mSwjOuL28TVS+dYCgaJl1I8T74cdIVIQUoLNHqyR7Nw95xgmV9KDiRIlXXFN2H/LMv4rCiv768Gmp78yYOIBBozFrXoltg9cqNmggU/KiYObW6b4box8VoNvrhCDbBiInMjx00MTmeG683LiRBgOy4jeAHmmQCOdwT4D0CIETYA5ea0wAZuxMvEbWm9h2dCqGuA6zwNTyegCyz0Xls=

sudo: false
