language: node_js
node_js: 11

env:
  global:
    - JEKYLL_ENV=production
    - JEKYLL_LOG_LEVEL=info
    - GH_REF=github.com/neard/neard.github.io.git
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
    - secure: JxS7Lpja5WtmvWCK3BAtSOchWnyrHWsECqIr7N2MiO+njQLaOYDkKF9nkCaF5lwJLGf5Fk84Kh/mx6sDcB9Vw0EyzT0yjLPExhF4k20ZI5SxJmt882FGw5NPwr8deWJM7KqntsyTK8MVcJNao5qycvyXeD80xD4/qhDOJ82YK8iBo/YR7CcUR7vxHFh0tjGj7YFRMwlZQkpxirUVdksFyUH9vsCEepWwIkbD/5ovICgGMtiEY3/yMcjzDaBwDT+CyupTacC1QhgsIGbxmfhqeAfYZCxqUNql6sNpQYuCfVtSJCXIMYom8zkAECD2GVX0JFLZVQYK235t5VREqAM/jhqqZT4WLKGj7hH3qOVnT7k+FublfyW+IhgxLQh72u7W7ZLQkgthIMADkjOZoVIHgfh7sp5J8Kh3Slb8LQKbrOBzVy/TSLj2H4U6588mC5Ddid76ro4M74vfprsRgJe8JwrIq7+szgklgiX3jcYmrOA8zhjtlxSpykLLYGxhM78Rj0QNnOszBSmuzay+bmev15yP9eUBPspaUbCKUacEaN/DMnVdxZPTKlqPmukVpXEEms4sqWMnTkHRottNM4GWCz1wCo+E8uroE+O1rge582TjkJHvmiGMcOsHMCgBcTJHCxC0ce4cUuKZi4FIX8nCQHml3yCCynZcUIQNPagKjmY= # GH_TOKEN

cache:
  yarn: true
  directories:
    - /home/travis/.rvm/

before_install:
  - rvm install 2.6.3
  - rvm use 2.6.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  - yarn install
  - gem install bundler
  - bundle install

script:
  - gulp --env=production build
  #- htmlproofer ./web --allow-hash-href --check-favicon --only-4xx --http-status-ignore "403" --alt-ignore "/.*/" --url-ignore "/#0/,/#lg/,/support.microsoft.com/" --log-level=:debug
  - ./deploy.sh

branches:
  only:
    - dev

notifications:
  email:
    recipients:
      - travisci@neard.io
    on_success: always
    on_failure: always
