language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.3.3
  - rvm use 2.3.3 --fuzzy
  - export GEMDIR=$(rvm gemdir)

before_script:
  - npm install -g bower
  - npm install -g gulp
  - bower install
  - gem install bundler
  - bundle install
  - chmod +x ./travis.sh

script: "./travis.sh"

branches:
  only:
    - master

env:
  global:
    - secure: JxS7Lpja5WtmvWCK3BAtSOchWnyrHWsECqIr7N2MiO+njQLaOYDkKF9nkCaF5lwJLGf5Fk84Kh/mx6sDcB9Vw0EyzT0yjLPExhF4k20ZI5SxJmt882FGw5NPwr8deWJM7KqntsyTK8MVcJNao5qycvyXeD80xD4/qhDOJ82YK8iBo/YR7CcUR7vxHFh0tjGj7YFRMwlZQkpxirUVdksFyUH9vsCEepWwIkbD/5ovICgGMtiEY3/yMcjzDaBwDT+CyupTacC1QhgsIGbxmfhqeAfYZCxqUNql6sNpQYuCfVtSJCXIMYom8zkAECD2GVX0JFLZVQYK235t5VREqAM/jhqqZT4WLKGj7hH3qOVnT7k+FublfyW+IhgxLQh72u7W7ZLQkgthIMADkjOZoVIHgfh7sp5J8Kh3Slb8LQKbrOBzVy/TSLj2H4U6588mC5Ddid76ro4M74vfprsRgJe8JwrIq7+szgklgiX3jcYmrOA8zhjtlxSpykLLYGxhM78Rj0QNnOszBSmuzay+bmev15yP9eUBPspaUbCKUacEaN/DMnVdxZPTKlqPmukVpXEEms4sqWMnTkHRottNM4GWCz1wCo+E8uroE+O1rge582TjkJHvmiGMcOsHMCgBcTJHCxC0ce4cUuKZi4FIX8nCQHml3yCCynZcUIQNPagKjmY=
    - JEKYLL_ENV=production
    - JEKYLL_LOG_LEVEL=debug
    - GH_REF=github.com/crazy-max/neard-website.git
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  slack:
    secure: Q5z9SE+a6BOfiJQpZbGrIloPayObtmEtKYDRwBYQwi5TJiCCt3G4RtvnBHy36DUL+CoNHxeHLCFU5cr2wW/Adu6TR9XoPgr08EIc9oqLiTrQONgDgwGqdk4NrqFLfg0UWVPgDLtfqE7nuAHGRdIeF9zHJX5Xe8xve3yhSsRY5FSoQv8ab0i1SKWSqFsV9JaQdSLyboeJRJv8p6RHt5ayxXY3gBh74qFbK7TGQcJhqhz0i+1CPIujFL6lp6sl8xI0cqx+mTf04mWjv+wovjjtl5c5aAKRhIC9ApT2AcvM8SZ0xxZ6TNsrwb9Wdc3QHH9fLUsDqKr5X+orHVJKQZ4e8i8SkloBDDLiiNRsArLpgzVRxrZ4NdFK+KRBFl26PkuN7k+2vdcpP0dtlKOdZy/ON0ENzt1vK2RGx4SUEGiD8y0VImElZ8doblTc41WKtPUmMn0zz20st/UUbH2vaoV4YpSWf6DbDBgNkCD2hoM8GiHAgnWHIkv1X+RQDXjep+OAfUPp7dEgNZ8e0J8muVbOAJuwevwHMj0Z+uqqnzvXKGgaFL4iq4K1hr9LHn3WM/wFQ9fNce4s3+Shbgi9mwk6sSsl2KDSLL2+0sUF7lkp8VZDQZ5+kLt/qOwRPS/eJvXOLtoyeJ9adZbSzl0weZ574G1mIBCImQCKJf15y+dih5o=

sudo: false
