name: website

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        # https://github.com/actions/setup-node
        name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 11
      -
        # https://github.com/actions/setup-ruby
        name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      -
        name: Set up Bundler
        run: |
          gem uninstall -aIx bundler
          gem install bundler -v 2.0.2
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Yarn install
        run: |
          yarn install
      -
        name: Bundle install
        run: |
          bundle install --jobs 4 --retry 3
      -
        name: Build
        env:
          JEKYLL_ENV: production
          JEKYLL_LOG_LEVEL: info
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gulp --env=production build
          #htmlproofer ./web/download --allow-missing-href --allow-hash-href --assume_extension --check-favicon --http-status-ignore 403 --only-4xx --alt-ignore "/.*/" --log-level=:debug
      -
        # https://github.com/crazy-max/ghaction-github-pages
        name: Deploy
        if: success() && github.event_name != 'pull_request'
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: master
          build_dir: web
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
